<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'IDOBJ_MOVE_CATEGORY' => 'Confirm moving',
	'MAIN_GROUP' => 'Main information',
	'NLS_LOCATION' => 'Location',
	'NLS_SPECIFICATION' => 'Specification',
	'NLS_ADDITIONAL_INFO' => 'Additional information',
	'NLS_ABOUT_OWNER' => 'About the owner',
	'NLS_ADDITIONAL_SERVICES' => 'Additional services',
	'NLS_ADDRESS' => 'Address',
	'NLS_ARRIVAL' => 'Check in',
	'NLS_SCHEDULE' => 'Schedule',
	'NLS_Apartment_Type' => 'Type',
	'NLS_BATHROOM_FACILITIES' => 'Equipment in the bathroom',
	'NLS_BUILDING_ASPECT' => 'The orientation of the house',
	'NLS_BUILDING_LOCATION_TYPE' => 'Location of the house',
	'NLS_BUILDING_YEAR_OF_CONSTRUCTION' => 'Year of Construction',
	'NLS_BUILDING_YEAR_OF_RENOVATION' => 'Renovation',
	'NLS_Bedding_Type' => 'Bedding Type',
	'NLS_CHILDREN_FACILITIES' => 'Equipment for children',
	'NLS_CITY' => 'City',
	'NLS_COUNTRY' => 'Country',
	'NLS_DESC' => 'Summary',
	'NLS_FLOOR' => 'Floor',
	'NLS_FOTO' => 'Photo',
	'NLS_FOTOS' => 'Photos',
	'NLS_FULL_DESCRIPTION' => 'Full description',
	'NLS_GPS_LOCATION' => 'GPS coordinates',
	'NLS_INDOOR_FACILITIES' => 'Indoor facilities',
	'NLS_KITCHEN_FACILITIES' => 'The equipment in the kitchen',
	'NLS_MAP' => 'Location',
	'NLS_MEANS_OF_ACCESS' => 'Means of access',
	'NLS_MINIMUM_RENTAL_PERIOD' => 'The minimum rental period',
	'NLS_MULTIMEDIA_FACILITIES' => 'Multimedia equipment',
	'NLS_NEIGHBORHOOD' => 'Suburbs',
	'NLS_NOTICES' => 'Notices',
	'NLS_NUMBER_OF_ROOMS' => 'Rooms',
	'NLS_NUMBER_OF_SLEEPERS' => 'Number of beds',
	'NLS_OUTDOOR_FACILITIES' => 'Outdoor facilities',
	'NLS_PETS_ALLOWANCE' => 'Pets',
	'NLS_PRICE' => 'Price',
	'NLS_REGION' => 'Location',
	'NLS_Room_Type' => 'Room Type',
	'NLS_SMOKING' => 'Smoke',
	'NLS_STATE' => 'State',
	'NLS_SUBREGION' => 'Sub',
	'NLS_SWIMING_POOL' => 'Pool',
	'NLS_TITLE' => 'Title',
	'NLS_USEFUL_INFO' => 'Useful Information',
	'NLS_VALUTA' => 'Currency',
	'BUSY' => 'Занято',
	'BUTTON_FIND' => 'Find',
	'CURRENT_DATE' => 'Current date',
	'DELETE_MARKER' => 'Delete marker',
	'FIND_ON_MAP' => 'Find on map',
	'FOTO_ON_MAIN' => 'The home',
	'FOTO_TO_MAIN' => 'Display on the main',
	'FREE' => 'Free',
	'IDOBJ_CATEGORY' => 'Category Ad',
	'LIFETIME_MONTH' => 'Month',
	'LIFETIME_SIX_MONTH' => 'Location of the Year',
	'LIFETIME_THREE_MONTH' => 'Three months',
	'LIFETIME_TWO_WEEK' => 'Two weeks',
	'LIFETIME_WEEK' => 'Week',
	'NOT_SELECT' => 'not selected',
	'NOT_SET_TYPE_FIELDS' => 'Do not set the field type.',
	'USER_CODE' => 'Code unification',
	'USER_CREATE_CODE' => 'Code Generation',
	'USER_PROFILE' => 'Profile',

);