<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'MAIL_ACTIVATION_ACTIVATION_LINK' => 'Confirm email',
	'MAIL_ACTIVATION_SUBJECT' => 'Account activation on Geo Joy',
	'MAIL_CONFIRMATION_SUBJECT' => 'Confirm email `and the Geo Joy',
	'MAIL_RESET_PASSWORD_LINK' => 'Reset Password',
	'MAIL_RESET_PASSWORD_SUBJECT' => 'Code to reset your password',
	'MAIL_CONFIRMATION_CONFIRMATION_LINK' => 'Confirm email',
	'MAIL_NEWS_ALL_NEWS_LINK' => 'View all news site',
	'MAIL_NEWS_SUBJECT' => 'Site News',
	'MAIL_NEW_MESSAGE_LINK' => 'New message',
	'MAIL_PRIVATE_MESSAGE_SUBJECT' => 'New message',


	'ACTIVATION_TITLE' => 'GeoJoy email activation',
	'ACTIVATION_SHORT_TEASER' => 'GeoJoy email activation',
	'ACTIVATION_HEADING' => 'Activate your new GeoJoy.com account',
	'ACTIVATION_GREETING' => 'Dear',
	'ACTIVATION_MAIN_TEXT' => 'Thank you for signing up with GeoJoy.com. Please confirm your registration by clicking the link below or copy/paste the link into your browser:',
	'ACTIVATION_SUB_TEXT' => 'Remember to Log-in to take advantage of the many features available to you as a registered user.',
	'ACTIVATION_FOLLOW_TWITTER_TEXT' => 'follow on Twitter',
	'ACTIVATION_FOLLOW_FACEBOOK_TEXT' => 'follow on Facebook',
	'ACTIVATION_FOLLOW_VK_TEXT' => 'follow on VKontakte',
	'ACTIVATION_BACK_EMAIL_TEXT' => 'Our mailing address is:',


	'RESET_PASSWORD_TITLE' => 'RESET_PASSWORD_TITLE',
	'RESET_PASSWORD_SHORT_TEASER' => 'RESET_PASSWORD_SHORT_TEASER',
	'RESET_PASSWORD_HEADING' => 'RESET_PASSWORD_HEADING Activate your new GeoJoy.com account',
	'RESET_PASSWORD_GREETING' => 'Dear',
	'RESET_PASSWORD_MAIN_TEXT' => 'RESET_PASSWORD_MAIN_TEXT Thank you for signing up with GeoJoy.com. Please confirm your registration by clicking the link below or copy/paste the link into your browser:',
	'RESET_PASSWORD_SUB_TEXT' => 'RESET_PASSWORD_SUB_TEXT Remember to Log-in to take advantage of the many features available to you as a registered user.',
	'RESET_PASSWORD_FOLLOW_TWITTER_TEXT' => 'follow on Twitter',
	'RESET_PASSWORD_FOLLOW_FACEBOOK_TEXT' => 'follow on Facebook',
	'RESET_PASSWORD_FOLLOW_VK_TEXT' => 'follow on VKontakte',
	'RESET_PASSWORD_BACK_EMAIL_TEXT' => 'Our mailing address is:',


	'CONFIRMATION_TITLE' => 'CONFIRMATION_TITLE',
	'CONFIRMATION_SHORT_TEASER' => 'CONFIRMATION_SHORT_TEASER',
	'CONFIRMATION_HEADING' => 'CONFIRMATION_HEADING Activate your new GeoJoy.com account',
	'CONFIRMATION_GREETING' => 'Dear',
	'CONFIRMATION_MAIN_TEXT' => 'CONFIRMATION_MAIN_TEXT Thank you for signing up with GeoJoy.com. Please confirm your registration by clicking the link below or copy/paste the link into your browser:',
	'CONFIRMATION_SUB_TEXT' => 'CONFIRMATION_SUB_TEXT Remember to Log-in to take advantage of the many features available to you as a registered user.',
	'CONFIRMATION_FOLLOW_TWITTER_TEXT' => 'follow on Twitter',
	'CONFIRMATION_FOLLOW_FACEBOOK_TEXT' => 'follow on Facebook',
	'CONFIRMATION_FOLLOW_VK_TEXT' => 'follow on VKontakte',
	'CONFIRMATION_BACK_EMAIL_TEXT' => 'Our mailing address is:',


	'NEWS_TITLE' => 'NEWS_TITLE',
	'NEWS_SHORT_TEASER' => 'NEWS_SHORT_TEASER',
	'NEWS_HEADING' => 'NEWS_HEADING Activate your new GeoJoy.com account',
	'NEWS_GREETING' => 'Dear',
	'NEWS_MAIN_TEXT' => 'NEWS_MAIN_TEXT Thank you for signing up with GeoJoy.com. Please confirm your registration by clicking the link below or copy/paste the link into your browser:',
	'NEWS_SUB_TEXT' => 'NEWS_SUB_TEXT Remember to Log-in to take advantage of the many features available to you as a registered user.',
	'NEWS_FOLLOW_TWITTER_TEXT' => 'follow on Twitter',
	'NEWS_FOLLOW_FACEBOOK_TEXT' => 'follow on Facebook',
	'NEWS_FOLLOW_VK_TEXT' => 'follow on VKontakte',
	'NEWS_BACK_EMAIL_TEXT' => 'Our mailing address is:',


	'PRIVATE_MESSAGE_TITLE' => 'PRIVATE_MESSAGE_TITLE',
	'PRIVATE_MESSAGE_SHORT_TEASER' => 'PRIVATE_MESSAGE_SHORT_TEASER',
	'PRIVATE_MESSAGE_HEADING' => 'PRIVATE_MESSAGE_HEADING Activate your new GeoJoy.com account',
	'PRIVATE_MESSAGE_GREETING' => 'Dear',
	'PRIVATE_MESSAGE_MAIN_TEXT' => 'PRIVATE_MESSAGE_MAIN_TEXT Thank you for signing up with GeoJoy.com. Please confirm your registration by clicking the link below or copy/paste the link into your browser:',
	'PRIVATE_MESSAGE_SUB_TEXT' => 'PRIVATE_MESSAGE_SUB_TEXT Remember to Log-in to take advantage of the many features available to you as a registered user.',
	'PRIVATE_MESSAGE_FOLLOW_TWITTER_TEXT' => 'follow on Twitter',
	'PRIVATE_MESSAGE_FOLLOW_FACEBOOK_TEXT' => 'follow on Facebook',
	'PRIVATE_MESSAGE_FOLLOW_VK_TEXT' => 'follow on VKontakte',
	'PRIVATE_MESSAGE_BACK_EMAIL_TEXT' => 'Our mailing address is:',

);