<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'ERROR_CREATED_TIES_NOT_LAST' => 'Это ошибка разработки, созданая связь поля должна быть последней для правильного определение ее индекса.',
	'ERROR_NOT_ALLOW_DEL_All_TIES' => 'Удаление всех связей полей запрещено.',
	'ERROR_NOT_PERMISSION_FOR_DEL_TIES' => 'У Вас нет прав на удаление связей полей.',
	'ERROR_NOT_PERMISSION_FOR_EDIT_USER' => 'У Вас нет прав на редактирование пользователя.',
	'ERROR_DISABLED_FIELD_IN_FILTER' => 'Use of disabled or not an existing field "{name}" in the filter.',
	'ERROR_FIELD_NOT_EXISTS' => 'This is an error of development, sought not an existing field.',
	'ERROR_INVALID_REQUEST' => 'The request contains an error.',
	'ERROR_IS_NOT_SET_PARAMETER_MAIN_TABLE' => 'This is an error of development, is not specified mainTable, required to run a class Managers',
	'ERROR_IS_NOT_SET_PARAMETER_SET_NAME' => 'This is an error of development, is not specified setName, required to run a class Managers',
	'ERROR_NOT_ALLOW_DEL_All_OBJECTS' => 'Empty parameter in the removal of multiple ads.',
	'ERROR_NOT_CREATE_OBJECT' => 'System error when creating ads, please try later or contact the administration.',
	'ERROR_NOT_UPDATE_OBJECT' => 'Системная ошибка при редактировании объявления, попробуйте пожалуйста позднее или обратитесь к администрации.',
	'ERROR_NOT_DELETE_OBJECT' => 'System error when removing ads, please try later or contact the administration.',
	'ERROR_NOT_FOUND_PAGE' => 'Page not found.',
	'ERROR_NOT_PERMISSION' => 'You do not have permission to perform this operation.',
	'ERROR_NOT_PERMISSION_FOR_DEL_OBJECT' => 'You have no right to remove the ads.',
	'ERROR_NOT_PERMISSION_FOR_DEL_USER' => 'You have no rights to delete users.',
	'ERROR_NOT_PERMISSION_SET_ROLE' => 'You are not authorized to set a user`s role.',
	'ERROR_SAVE_IMAGE' => 'Failed to save the image.',
	'ERROR_UPLOAD_NOT_JPG' => 'This is not a jpg image.',
	'ERROR_NOT_RESET_PASSWORD' => 'Системная ошибка при сбросе пароля, попробуйте пожалуйста позднее или обратитесь к администрации.',

);