<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'ERROR_POSIBLE_NOT_CORRECT_EMAIL' => 'Error sending email. Set may not existing {email} or a system error. Try after by or contact the administrator. ',
	'FIELD_COMPANY_NAME' => 'Company',
	'FIELD_ABOUT_ME' => 'About Me',
	'FIELD_AVATAR' => 'Avatar',
	'FIELD_CITY' => 'City',
	'FIELD_COMPANY' => 'Company',
	'FIELD_COUNTRY' => 'Country',
	'FIELD_EMAIL' => 'Email',
	'FIELD_FRIENDS_COUNT' => 'Number of friends',
	'FIELD_KARMA' => 'Karma',
	'FIELD_LANGUAGES' => 'Spoken languages',
	'FIELD_MAIN_LANGUAGE' => 'Main language',
	'FIELD_NAME' => 'Name',
	'FIELD_PASSWORD' => 'Password',
	'FIELD_PASSWORD2' => 'Confirm Password',
	'FIELD_PASSWORD_OLD' => 'Current password',
	'FIELD_TEL' => 'Phone',
	'SOCIAL_INFO_CITY' => 'City',
	'SOCIAL_INFO_COUNTRY' => 'Country',
	'SOCIAL_INFO_CREATED' => 'Profile created',
	'SOCIAL_INFO_FIRST_NAME' => 'Name',
	'SOCIAL_INFO_FOLLOWERS' => 'Tweet',
	'SOCIAL_INFO_FRIENDS' => 'Friends',
	'SOCIAL_INFO_FULL_NAME' => 'User',
	'SOCIAL_INFO_GENDER' => 'Sex',
	'SOCIAL_INFO_LAST_NAME' => 'Last Name',
	'SOCIAL_INFO_LINK' => 'Profile Link',
	'SOCIAL_INFO_NICKNAME' => 'Username',
	'SOCIAL_INFO_PROFILE_IMAGE' => 'Profile Image',
	'FOR_ALL' => 'All',
	'FOR_ME' => 'To me',
	'FOR_MULTIUSER' => 'For my accounts',
	'FOR_REGISTERED' => 'For registered',
	'OPTIONS_SAVES' => 'Settings have been saved.',

);