<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'IDOBJ_MOVE_CATEGORY' => 'Подтвердить перемещение',
	'MAIN_GROUP' => 'Основная информация',
	'NLS_LOCATION' => 'Местоположение',
	'NLS_SPECIFICATION' => 'Параметры',
	'NLS_ADDITIONAL_INFO' => 'Дополнительные параметры',
	'NLS_ABOUT_OWNER' => 'О владельце',
	'NLS_ADDITIONAL_SERVICES' => 'Дополнительные услуги',
	'NLS_ADDRESS' => 'Адрес',
	'NLS_ARRIVAL' => 'Заселение',
	'NLS_SCHEDULE' => 'Расписание',
	'NLS_Apartment_Type' => 'Тип',
	'NLS_BATHROOM_FACILITIES' => 'Оборудование в ванной',
	'NLS_BUILDING_ASPECT' => 'Ориентация дома',
	'NLS_BUILDING_LOCATION_TYPE' => 'Местоположение дома',
	'NLS_BUILDING_YEAR_OF_CONSTRUCTION' => 'Год постройки',
	'NLS_BUILDING_YEAR_OF_RENOVATION' => 'Год реконструкции',
	'NLS_Bedding_Type' => 'Тип спального места',
	'NLS_CHILDREN_FACILITIES' => 'Оборудование для детей',
	'NLS_CITY' => 'Город',
	'NLS_COUNTRY' => 'Страна',
	'NLS_DESC' => 'Краткое описание',
	'NLS_FLOOR' => 'Этаж',
	'NLS_FOTO' => 'Фотография',
	'NLS_FOTOS' => 'Фотографии',
	'NLS_FULL_DESCRIPTION' => 'Полное описание',
	'NLS_GPS_LOCATION' => 'GPS координаты',
	'NLS_INDOOR_FACILITIES' => 'Внутреннее оборудование',
	'NLS_KITCHEN_FACILITIES' => 'Оборудование в кухне',
	'NLS_MAP' => 'Расположение на карте',
	'NLS_MEANS_OF_ACCESS' => 'Средства доступа',
	'NLS_MINIMUM_RENTAL_PERIOD' => 'Минимальный период аренды',
	'NLS_MULTIMEDIA_FACILITIES' => 'Мультимедийное оборудование',
	'NLS_NEIGHBORHOOD' => 'Окрестности',
	'NLS_NOTICES' => 'Примечания',
	'NLS_NUMBER_OF_ROOMS' => 'Кол-во комнат',
	'NLS_NUMBER_OF_SLEEPERS' => 'Кол-во спальных мест',
	'NLS_OUTDOOR_FACILITIES' => 'Уличное оборудование',
	'NLS_PETS_ALLOWANCE' => 'Домашние животные',
	'NLS_PRICE' => 'Цена',
	'NLS_REGION' => 'Регион',
	'NLS_Room_Type' => 'Тип комнаты',
	'NLS_SMOKING' => 'Курение',
	'NLS_STATE' => 'Область',
	'NLS_SUBREGION' => 'Подрегион',
	'NLS_SWIMING_POOL' => 'Бассейн',
	'NLS_TITLE' => 'Заголовок',
	'NLS_USEFUL_INFO' => 'Полезная информация',
	'NLS_VALUTA' => 'Валюта',
	'BUSY' => 'Занято',
	'BUTTON_FIND' => 'Найти',
	'CURRENT_DATE' => 'Текущая дата',
	'DELETE_MARKER' => 'Удалить маркер',
	'FIND_ON_MAP' => 'Найти на карте:',
	'FOTO_ON_MAIN' => 'На главной',
	'FOTO_TO_MAIN' => 'Выводить на главной',
	'FREE' => 'Свободно',
	'IDOBJ_CATEGORY' => 'Категория объявления',
	'LIFETIME_MONTH' => 'Месяц',
	'LIFETIME_SIX_MONTH' => 'Пол года',
	'LIFETIME_THREE_MONTH' => 'Три месяца',
	'LIFETIME_TWO_WEEK' => 'Две недели',
	'LIFETIME_WEEK' => 'Неделя',
	'NOT_SELECT' => 'не выбрано',
	'NOT_SET_TYPE_FIELDS' => 'Не задано тип поля.',
	'USER_CODE' => 'Код объединения',
	'USER_CREATE_CODE' => 'Генерация кода',
	'USER_PROFILE' => 'Профиль пользователя',

);