<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'ERROR_CREATED_TIES_NOT_LAST' => 'Это ошибка разработки, созданая связь поля должна быть последней для правильного определение ее индекса.',
	'ERROR_NOT_ALLOW_DEL_All_TIES' => 'Удаление всех связей полей запрещено.',
	'ERROR_NOT_PERMISSION_FOR_DEL_TIES' => 'У Вас нет прав на удаление связей полей.',
	'ERROR_NOT_PERMISSION_FOR_EDIT_USER' => 'У Вас нет прав на редактирование пользователя.',
	'ERROR_DISABLED_FIELD_IN_FILTER' => 'Использование отключенного или не существующего поля "{name}" в фильтре.',
	'ERROR_FIELD_NOT_EXISTS' => 'Это ошибка разработки, запрошено не существующее поле.',
	'ERROR_INVALID_REQUEST' => 'Запрос содержит ошибку.',
	'ERROR_IS_NOT_SET_PARAMETER_MAIN_TABLE' => 'Это ошибка разработки, не задан параметр mainTable, необходимый для работы класса Managers',
	'ERROR_IS_NOT_SET_PARAMETER_SET_NAME' => 'Это ошибка разработки, не задан параметр setName, необходимый для работы класса Managers',
	'ERROR_NOT_ALLOW_DEL_All_OBJECTS' => 'Пустой параметр в функции множественного удаления объявлений.',
	'ERROR_NOT_CREATE_OBJECT' => 'Системная ошибка при создании объявления, попробуйте пожалуйста позднее или обратитесь к администрации.',
	'ERROR_NOT_UPDATE_OBJECT' => 'Системная ошибка при редактировании объявления, попробуйте пожалуйста позднее или обратитесь к администрации.',
	'ERROR_NOT_DELETE_OBJECT' => 'Системная ошибка при удалении объявления, попробуйте пожалуйста позднее или обратитесь к администрации.',
	'ERROR_NOT_FOUND_PAGE' => 'Страница не найдена.',
	'ERROR_NOT_PERMISSION' => 'У Вас нет прав для выполнения данной операции.',
	'ERROR_NOT_PERMISSION_FOR_DEL_OBJECT' => 'У Вас нету прав для удаления объявления.',
	'ERROR_NOT_PERMISSION_FOR_DEL_USER' => 'У Вас нет прав для удаления пользователей.',
	'ERROR_NOT_PERMISSION_SET_ROLE' => 'У Вас нет прав для задания такой роли пользователю.',
	'ERROR_SAVE_IMAGE' => 'Ошибка сохранения изображения.',
	'ERROR_UPLOAD_NOT_JPG' => 'Это не jpg изображение.',
	'ERROR_NOT_RESET_PASSWORD' => 'Системная ошибка при сбросе пароля, попробуйте пожалуйста позднее или обратитесь к администрации.',

);