<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $1
 */
return array (

	'ERROR_POSIBLE_NOT_CORRECT_EMAIL' => 'Ошибка отправки письма. Возможно указан не существующий {email} или это системная ошибка. Попробуйте поже или обратитесь к администратору.',
	'FIELD_COMPANY_NAME' => 'Компания',
	'FIELD_ABOUT_ME' => 'О себе',
	'FIELD_AVATAR' => 'Аватар',
	'FIELD_CITY' => 'Город',
	'FIELD_COMPANY' => 'Компания',
	'FIELD_COUNTRY' => 'Страна',
	'FIELD_EMAIL' => 'Email',
	'FIELD_FRIENDS_COUNT' => 'Количество друзей',
	'FIELD_KARMA' => 'Карма',
	'FIELD_LANGUAGES' => 'Языки общения',
	'FIELD_MAIN_LANGUAGE' => 'Основной язык',
	'FIELD_NAME' => 'Имя',
	'FIELD_PASSWORD' => 'Пароль',
	'FIELD_PASSWORD2' => 'Пароль повторно',
	'FIELD_PASSWORD_OLD' => 'Текущий пароль',
	'FIELD_TEL' => 'Телефон',
	'SOCIAL_INFO_CITY' => 'Город',
	'SOCIAL_INFO_COUNTRY' => 'Страна',
	'SOCIAL_INFO_CREATED' => 'Профиль создан',
	'SOCIAL_INFO_FIRST_NAME' => 'Имя',
	'SOCIAL_INFO_FOLLOWERS' => 'Твитов',
	'SOCIAL_INFO_FRIENDS' => 'Друзей',
	'SOCIAL_INFO_FULL_NAME' => 'Пользователь',
	'SOCIAL_INFO_GENDER' => 'Пол',
	'SOCIAL_INFO_LAST_NAME' => 'Фамилия',
	'SOCIAL_INFO_LINK' => 'Ссылка на профиль',
	'SOCIAL_INFO_NICKNAME' => 'Ник',
	'SOCIAL_INFO_PROFILE_IMAGE' => 'Изображение профиля',
	'FOR_ALL' => 'Для всех',
	'FOR_ME' => 'Для меня',
	'FOR_MULTIUSER' => 'Для моих аккаунтов',
	'FOR_REGISTERED' => 'Для зарегистрированных',
	'OPTIONS_SAVES' => 'Настройки сохранены.',

);